### ISSUE TITLE
Products schema may be incomplete.

### ISSUE THREAD

**Issue by declaresub** [plaid/plaid-openapi#184]
The OpenAPI schema for Products appears to be incomplete.  The products list for institution ins_127989, Bank of America, includes the value "transactions_refresh" that is not in the products schema.  This value is also returned for a few other institutions.

**Comment by phoenixy1** [comment]
Thank you for reporting this, we will fix it in the next release of the client libraries! 
Since you're reporting this in the context of creating a client library, I will add as a note that Plaid does consider adding enum values to be a non-breaking API change, so your client library should be robust to seeing an enum value that it doesn't know about: https://plaid.com/docs/api/versioning/#api-versioning

**Comment by phoenixy1** [comment]
Update: Fix has been merged and will be shipped in the next client library release (probably in January).
